apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      initContainers:
      - name: copy-config
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          echo "Copying configuration template..."
          cp /config-templates/configuration.yaml /config/configuration.yaml
          echo "Configuration copied successfully"
        volumeMounts:
        - name: homeassistant-data
          mountPath: /config
        - name: homeassistant-config
          mountPath: /config-templates
      containers:
      - name: homeassistant
        image: homeassistant/home-assistant:latest
        ports:
        - containerPort: 8123
        env:
        - name: TZ
          value: "UTC"
        volumeMounts:
        - name: homeassistant-data
          mountPath: /config
        - name: homeassistant-config
          mountPath: /config-templates
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        securityContext:
          privileged: true
      volumes:
      - name: homeassistant-data
        persistentVolumeClaim:
          claimName: homeassistant-data
      - name: homeassistant-config
        configMap:
          name: homeassistant-config
