apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kasm-data
  namespace: kasm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi

