apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homarr

resources:
- namespace.yaml
- pvc.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- httproute.yaml

labels:
  app.kubernetes.io/name: homarr
  app.kubernetes.io/managed-by: argocd
