apiVersion: v1
kind: Secret
metadata:
  name: homarr-secrets
  namespace: homarr
type: Opaque
data:
  # This is a template file - safe to commit
  # The actual secret will be created by running: ./scripts/generate-homarr-secret.sh
  # This placeholder will be replaced with a real base64-encoded key
  encryption-key: UkFIZllIR3RSWUVqcndLeURTeGFWN0dGcHV3VmRhUlJaTWJJa0NDMTlqQT0=
